name: Integration Test

on:
  push:
    branches: ["main"]

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  azure-function-core-tools:
    runs-on: ubuntu-latest
    name: Run integration tests
    env:
        CUSTOMCONNSTR_AZURE_STORAGE: "UseDevelopmentStorage=true"
        FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"

    steps:
    - name: Echo envs
      run: echo "CUSTOMCONNSTR_AZURE_STORAGE is $CUSTOMCONNSTR_AZURE_STORAGE and FUNCTIONS_WORKER_RUNTIME is $FUNCTIONS_WORKER_RUNTIME"

    - name: Checkout branch
      uses: actions/checkout@v4

    - name: Setup .NET v${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore ImageProcessor dependencies
      run: |
        dotnet restore ImageProcessor/ImageProcessor.csproj

    - name: Build ImageProcessor
      run: |
        dotnet build ImageProcessor/ImageProcessor.csproj --configuration Release --no-restore

    - name: Install Azure Function Core Tools
      run: npm i -g azure-functions-core-tools@4

    - name: Run ImageProcessor
      run: |
        cd ImageProcessor
        func host start &
        echo "ImageProcessor started in the background"

    - name: Wait for ImageProcessor to launch
      run: |
        for i in {1..10}; do
        if curl -s http://localhost:7071 > /dev/null; then
            echo "ImageProcessor is ready"
            curl --request POST http://localhost:7071/api/imagevalidator
            exit 0
        fi
        echo "Waiting for ImageProcessor to start..."
        sleep 2
        done
        echo "ImageProcessor did not start in time"
        exit 1

    - name: Make a request to running ImageProcessor 2
      run: curl --request POST http://localhost:7071/api/imagevalidator

    - name: Make a request to running ImageProcessor 1
      run: curl --request POST http://localhost:7071/api/imagevalidator --data '{"file":"works"}'

    - name: Stop ImageProcessor
      run: pkill -f "func host start"
        
